spring:
  application:
    name: confidential-client-app
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: confidential-client-app
            client-secret: 1MhzmPdRSk8ROte3ksOpQ7ZfrkI2DxqP
            authorization-grant-type: authorization_code
            scope: openid, profile, email
            client-authentication-method: client_secret_basic
            redirect-uri: "http://localhost:9098/login/oauth2/code/keycloak"

        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/spring-authentication-code-flow-realm
            user-name-attribute: preferred_username

server:
  port: 9098

keycloak:
  client:
    id: confidential-client-app
  logout:
    url: "http://localhost:8080/realms/spring-authentication-code-flow-realm/protocol/openid-connect/logout"
    redirect-uri: "http://localhost:9097/"

logging:
  level:
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO